# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dingg' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Dingg



  platform :ios, '9.0'
  target 'DinggTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Dingg-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Dingg-tvOS

  target 'Dingg-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
