module.exports = {
    COLOR: {
      ORANGE: '#ffa400',
      GRAY: '#999999',
      ShadowColor: 'rgb(220,220,220)',
      input_color:"rgb(201,201,201)",
      backgroundColor: "white",
      fontfamily: "Muli-Bold",
      FontFamilyBold:"Muli-ExtraBold",
      rootBAckgroundColor:"rgb(243,242,242)",
      _width : 330,
       _height : 2,
       Logo_width:110,
       Logo_height:77,
       Icon_divider_width:3,
       Icon_divider_height:23
    },
    Logo : require('../Image/icon/logo_3.png'),
    Plus_icon : require('../Image/icon/plus.png'),
    Delete_icon : require('../Image/main/deleteImage3x.png'),
    Serve_Icon: require('../Image/main/serveTimeIcon3x.png'),
    Calender_Icon: require('../Image/main/calenderIcon3x.png'),
    Arrow_image : require('../Image/icon/arrow_right.png'),
    UnSelectIcon:require('../Image/main/unselectedIcon3x.png') ,
    SelectIcon:  require('../Image/main/selectedIcon3x.png'),
    CancelIcon:  require('../Image/icon/cancel1.png'),
    TableDivider:  require('../Image/main/tableDivider2x.png'),
    Icon_width : 18,
    Icon_height : 18,
    Accept:  require('../Image/main/acceptIcon3x.png'),
    Reject:  require('../Image/main/rejectIcon3x.png'),
    Notification:  require('../Image/icon/notificationIcon3x.png'),
    Notification_yellow:  require('../Image/icon/notificationIconYellow3x2.png'),
    Highlight_Top_tab:  require('../Image/main/highlight3x.png'),
    Highlight_top_tab_invi:  require('../Image/main/line-transparent-vertical-2.png'),
    QR_Code:  require('../Image/main/qrCode3x.jpg'),
    Delete_image:  require('../Image/icon/deleteIcon2x.png'),
    Edit_image:  require('../Image/icon/editIcon2x.png'),
    SERve_image:  require('../Image/icon/serviceIcon3x.png'),


  };