import {widthPercentageToDP as wp, heightPercentageToDP as hp} from 'react-native-responsive-screen';
import RF from "react-native-responsive-fontsize"

module.exports = {
    COLOR: {
      Black: '#444444',
      ORANGE: '#ffa400',
      GRAY: '#999999',
      ShadowColor: 'rgb(220,220,220)',
      input_color:"rgb(201,201,201)",
      backgroundColor: "white",   
      fontfamily: "Muli-Bold",
      FontFamilyBold:"Muli-ExtraBold",
      rootBAckgroundColor:"rgb(243,242,242)",
      White_color:"white",
      _width : 330,
       _height : 2,
       Logo_width:90,
       Logo_height:64,
       Icon_divider_width:3,
       Icon_divider_height:23,
       Icon_width:23,
       Yellow_10:10,
       Yellow_50 :50,
       Size_250 :250,
       Size_15:15,
       Size_60:60,
       Size_35:35,Size_8:8,
       Size_100:100,Size_21:21,Size_27:27,size_75:75,size_12:12
    },
    Header:{fontWeight: 'bold',marginBottom:hp("2%"),fontSize: RF("2.4"),justifyContent:"center",alignItems:"center"
  },
    Logo : require('../Image/icon/logo_3.png'),
    Plus_icon : require('../Image/icon/plus.png'),
    Plus_icon_stylist : require('../Image/icon/plusIconbig3x2.png'),
    Delete_icon : require('../Image/main/deleteImage3x.png'),
    Serve_Icon: require('../Image/main/serveTimeIcon3x.png'),
    Calender_Icon: require('../Image/main/calenderIcon3x.png'),
    Arrow_image : require('../Image/icon/arrow_right.png'),
    UnSelectIcon:require('../Image/main/unselectedIcon3x.png') ,
    SelectIcon:  require('../Image/main/selectedIcon3x.png'),
    CancelIcon:  require('../Image/icon/cancel1.png'),
    TableDivider:  require('../Image/main/tableDivider2x.png'),
    Icon_width : 18,
    Icon_height : 18,
    Accept:  require('../Image/main/acceptIcon3x.png'),
    Reject:  require('../Image/main/rejectIcon3x.png'),
    Notification:  require('../Image/icon/notificationIcon3x.png'),
    Notification_yellow:  require('../Image/icon/notificationIconYellow3x2.png'),
    Highlight_Top_tab:  require('../Image/main/highlight3x.png'),
    Highlight_top_tab_invi:  require('../Image/main/line-transparent-vertical-2.png'),
    QR_Code:  require('../Image/main/qrCode3x.jpg'),
    Delete_image:  require('../Image/icon/deleteIcon2x.png'),
    Edit_image:  require('../Image/icon/editIcon2x.png'),
    SERve_image:  require('../Image/icon/serviceIcon3x.png'),
    Icon_Divider : require('../Image/main/iconDivider3x.png'),
    Left_Yellow_arrow : require('../Image/main/leftArrow3x.png'),
    Right_yellow_arrow : require('../Image/main/rightArrow3x.png'),
    Plus_yellow_icon : require('../Image/main/addTimeIcon3x.png'),
    Edit_Camera : require('../Image/main/editButton3x.png'),
    Welcome_icon : require('../Image/icon/illustration3x.png'),
    Back_button : require('../Image/icon/back_2x.png'),
    Yellow_line : require('../Image/main/highlight3x.png'),
    Yullow_off_line : require('../Image/main/line-transparent-vertical-2.png'),
    Dashboard : require('../Image/icon/dashboard_yellow2x.png'),
    Dashboard_yellow : require('../Image/icon/dashboardIcon.png'),
    Queue_req : require('../Image/icon/queueRequest_yellow2x.png'),
    Que_req_white : require('../Image/icon/queueRequestIcon2x.png'),
    Queue : require('../Image/icon/queueIcon_yellow2x.png'),
    Queue_white : require('../Image/icon/queueIcon2x.png'),
    History : require('../Image/icon/historyIcon_yellow2x.png'),
    History_white : require('../Image/icon/historyIcon2x.png'),
    Setting : require('../Image/icon/settingsIcon_yellow2x.png'),
    Setting_white : require('../Image/icon/settingsIcon2x.png'),
    Profile : require('../Image/icon/profileIcon_yellow2x.png'),
    Profile_white : require('../Image/icon/profileIcon2x.png'),
    rectangle_line : require('../Image/icon/Line/rectangle1.png'),
    Copy_right : require('../Image/icon/copyright.png'),
    edit_icon : require('../Image/main/editButtonmain3x.png'),
    Loader : require('../Image/main/Ellipsis.gif'),

  };